### ISSUE TITLE
Missing import files in edk2_dependence.project

### ISSUE THREAD

**Issue by yu-se** [shafiuzzaman-md/stase#1]
Hello,
I'm attempting to run this project and have encountered an issue at the end of Part 1 (Rule-based Static Analysis). Specifically, two files that are imported in `edk2_dependence.project` appear to be missing:

1. `/home/Downloads/testrules/utils/utils.dl`
2. `/home/Downloads/testrules/utils/exports/utils-outputs.dl`

These files are referenced in `edk2_dependence.project` with the following include statements:

```datalog
#include "/home/Downloads/testrules/utils/utils.dl"
#include "/home/Downloads/testrules/utils/exports/utils-outputs.dl"
```
Are these files supposed to be part of the repository?
If not, where can I obtain these files? could you provide guidance on how to generate or create these files?

**Comment by achintyadesai** [comment]
Thanks for your interest. Both `/home/Downloads/testrules/utils/utils.dl` and `/home/Downloads/testrules/utils/exports/utils-outputs.dl` were part of another project and no longer needed. You can safely comment out both the lines and the `Souffle` command should run as expected.
We will update the file by removing the two lines. Let us know if it does not work.
